#
###################################
# Site wide configuration
####################################
#
title: Jimmy Ye
email:
description: Blog of a recent graduate of University of California, San Diego, with MS in Computer science.
url: # the base hostname & protocol for your site


#
###################################
# Jekyll configuration
####################################
#
timezone:          America/Los_Angeles
markdown:          kramdown
highlighter:       rouge
excerpt_separator: <!--more-->
permalink:         /articles/:year-:month/:title

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  enable_coderay: false

#
###################################
# Site Owner configuration
####################################
#
owner:
  name: Jimmy Ye
  avatar: avatar.jpg
  job: ""
  bio: "I spend way too much time reading about math and CS and tech and stuff."
  email: jiy162@ucsd.edu
  disqus-shortname:
  twitter: #username
  facebook: #username
  google:
    plus: #username
    analytics:
    verify:
    ad-client:
    ad-slot:
  bing-verify:
  github: rationalis
  gitlab: #username
  stackoverflow: 1277472/rationalis
  linkedin: jimmy-ye-a3333b82
  skype: #username
  xing: #username
  instagram: #username
  lastfm: #username
  tumblr: #username
  pinterest: #username
  foursquare: #username
  steam: #username
  dribbble: #username
  youtube: #username
  soundcloud: #username
  weibo: #username
  flickr: #username
  500px: #username
  codepen: #username
